from dataclasses import dataclass
from typing import List


@dataclass
class SaasSignature:
    name: str
    cname_patterns: List[str]
    fingerprints: List[str]
    remediation: str


SAAS_TAKEOVER_SIGNATURES: List[SaasSignature] = [
    SaasSignature(
        name="Unbounce",
        cname_patterns=["unbouncepages.com"],
        fingerprints=["The requested URL was not found on this server"],
        remediation="Delete the dangling CNAME DNS record in your DNS manager or re-attach the custom domain in Unbounce.",
    ),
    SaasSignature(
        name="GitHub Pages",
        cname_patterns=["github.io"],
        fingerprints=[
            "There isn't a GitHub Pages site here",
            "For root URLs (like http://example.com/) you must provide an index.html file",
        ],
        remediation="Remove the CNAME pointing to github.io or add the domain to a designated GitHub repository's custom domains settings.",
    ),
    SaasSignature(
        name="AWS S3",
        cname_patterns=["s3.amazonaws.com", "s3-website", ".s3."],
        fingerprints=["NoSuchBucket", "The specified bucket does not exist"],
        remediation="Either create the matching S3 bucket name in your AWS account or remove the orphaned CNAME record.",
    ),
    SaasSignature(
        name="AWS CloudFront",
        cname_patterns=["cloudfront.net"],
        fingerprints=["Bad request.", "ERROR: The request could not be satisfied", "Generated by cloudfront"],
        remediation="Ensure the alternate domain name (CNAME) is configured on an active CloudFront distribution, or remove the DNS record.",
    ),
    SaasSignature(
        name="Heroku",
        cname_patterns=["herokudns.com", "herokuapp.com"],
        fingerprints=["No such app", "Heroku | No such app"],
        remediation="Remove the Heroku CNAME record from DNS or provision the domain under an active Heroku application.",
    ),
    SaasSignature(
        name="Shopify",
        cname_patterns=["myshopify.com"],
        fingerprints=["Sorry, this shop is currently unavailable", "You'll be able to visit this store soon"],
        remediation="Remove the DNS entry or claim the domain inside your active Shopify store admin panel.",
    ),
    SaasSignature(
        name="Webflow",
        cname_patterns=["proxy.webflow.com", "webflow.io"],
        fingerprints=["The page you are looking for doesn't exist", "The site you are looking for could not be found"],
        remediation="Unlink the DNS mapping or assign the custom domain to a published Webflow project.",
    ),
    SaasSignature(
        name="Zendesk",
        cname_patterns=["zendesk.com"],
        fingerprints=["Help Center Closed", "No help center found"],
        remediation="Remove the CNAME or re-associate it with your active Zendesk Help Center instance.",
    ),
    SaasSignature(
        name="Pantheon",
        cname_patterns=["pantheonsite.io"],
        fingerprints=["The gods are wise, but do not know of the site which you seek"],
        remediation="Delete the CNAME record or bind the hostname to your active Pantheon environment.",
    ),
    SaasSignature(
        name="Netlify",
        cname_patterns=["netlify.app", "netlify.com"],
        fingerprints=["Not Found - Request ID", "Page Not Found - Netlify"],
        remediation="Claim this domain in your Netlify team account or delete the CNAME record immediately.",
    ),
    SaasSignature(
        name="Surge.sh",
        cname_patterns=["surge.sh"],
        fingerprints=["project not found"],
        remediation="Claim the custom domain using `surge --domain` or delete the DNS record.",
    ),
    SaasSignature(
        name="Fly.io",
        cname_patterns=["fly.dev"],
        fingerprints=["404 Not Found", "Could not find that app"],
        remediation="Remove the DNS CNAME record or configure a matching Fly.io certificate and application.",
    ),
    SaasSignature(
        name="HubSpot",
        cname_patterns=["hubspot.net"],
        fingerprints=["Domain not found", "HubSpot page not found"],
        remediation="Remove the CNAME or bind the domain inside HubSpot CMS settings.",
    ),
    SaasSignature(
        name="Ghost",
        cname_patterns=["ghost.io"],
        fingerprints=["The thing you were looking for is no longer here", "Fastly error: unknown domain"],
        remediation="Delete the CNAME pointing to ghost.io or update your publication domain in Ghost.",
    ),
    SaasSignature(
        name="Readme.io",
        cname_patterns=["readme.io"],
        fingerprints=["Project doesnt exist... yet!", "Project doesn't exist"],
        remediation="Remove CNAME mapping to Readme.io or claim the project name.",
    ),
    SaasSignature(
        name="UserVoice",
        cname_patterns=["uservoice.com"],
        fingerprints=["This UserVoice instance is no longer active", "This UserVoice subdomain is available"],
        remediation="Remove the UserVoice CNAME record.",
    ),
    SaasSignature(
        name="WordPress.com",
        cname_patterns=["wordpress.com"],
        fingerprints=["Do you want to register", "is not available"],
        remediation="Remove the WordPress.com CNAME or complete custom domain mapping.",
    ),
]
